"""intString

Revision ID: 368cd95dacc8
Revises: ba9e950e99a0
Create Date: 2025-06-12 19:54:21.327836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368cd95dacc8'
down_revision = 'ba9e950e99a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
