"""attLastDance

Revision ID: 4efd6e31bdd7
Revises: c61f130ec91a
Create Date: 2025-06-03 17:40:43.045676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efd6e31bdd7'
down_revision = 'c61f130ec91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    op.drop_table('model_version')
    # ### end Alembic commands ###
