"""AttModelVersion

Revision ID: 7094adb1cf96
Revises: f7d6a4500dc1
Create Date: 2025-06-11 11:04:28.939886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7094adb1cf96'
down_revision = 'f7d6a4500dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_directory', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('real_model', sa.Boolean(), nullable=False))
        batch_op.drop_column('train_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_number', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('real_model')
        batch_op.drop_column('train_directory')

    # ### end Alembic commands ###
