"""attNullableId

Revision ID: 82b46ffa91a6
Revises: 8befe736118c
Create Date: 2025-05-17 02:24:30.699551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b46ffa91a6'
down_revision = '8befe736118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('predio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('fachada',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fachada',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('predio',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
