"""AttBanco

Revision ID: 8befe736118c
Revises: 805c3624842d
Create Date: 2025-05-17 02:09:43.433765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8befe736118c'
down_revision = '805c3624842d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predio', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fachada', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('images_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'building', ['building_id'], ['id'])
        batch_op.drop_column('latitude')
        batch_op.drop_column('project_id')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_project_id_fkey', 'project', ['project_id'], ['id'])
        batch_op.drop_column('building_id')
        batch_op.drop_column('fachada')

    op.drop_table('building')
    # ### end Alembic commands ###
