"""Teste

Revision ID: 8fb26d9273f8
Revises: 
Create Date: 2025-05-14 22:11:35.198828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fb26d9273f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.alter_column('datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('veredict',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_index('IX_images_id_project')
        batch_op.drop_constraint('FK_images_project_id_project', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('raw_img')
        batch_op.drop_column('id_project')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('mensage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_index('IX_logs_id_images')
        batch_op.drop_index('IX_logs_id_user')
        batch_op.drop_constraint('FK_logs_users_id_user', type_='foreignkey')
        batch_op.drop_constraint('FK_logs_images_id_images', type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['image_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('id_user')
        batch_op.drop_column('id_images')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('contractor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False)

        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('contractor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_images', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_logs_images_id_images', 'images', ['id_images'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_logs_users_id_user', 'users', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.create_index('IX_logs_id_user', ['id_user'], unique=False)
        batch_op.create_index('IX_logs_id_images', ['id_images'], unique=False)
        batch_op.alter_column('mensage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('image_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_project', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('raw_img', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_images_project_id_project', 'project', ['id_project'], ['id'], ondelete='CASCADE')
        batch_op.create_index('IX_images_id_project', ['id_project'], unique=False)
        batch_op.alter_column('veredict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('datetime',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.drop_column('project_id')
        batch_op.drop_column('raw_image')

    # ### end Alembic commands ###
