"""addFKImage

Revision ID: 97d1e2b2f86a
Revises: e86682f11745
Create Date: 2025-06-11 11:50:26.517072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d1e2b2f86a'
down_revision = 'e86682f11745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fissure_id', sa.Integer(), nullable=False))
        batch_op.alter_column('veredict',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'fissure', ['fissure_id'], ['id'])
        batch_op.drop_column('fissure_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fissure_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('veredict',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('fissure_id')

    # ### end Alembic commands ###
