"""CorrigeVeredito

Revision ID: b104ec5ff352
Revises: bdcb15968a09
Create Date: 2025-05-14 22:41:55.917838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b104ec5ff352'
down_revision = 'bdcb15968a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('fresh_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('veredict',
               existing_type=sa.VARCHAR(),
               nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('veredict',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fresh_img',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
