"""addNjNJKBDJK

Revision ID: ba9e950e99a0
Revises: 36c58906eaad
Create Date: 2025-06-12 14:50:17.156704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9e950e99a0'
down_revision = '36c58906eaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column(
            'datetime',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="datetime::timestamp without time zone"
        )

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="date::timestamp without time zone"
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('date')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
