"""ArrumaRelacao

Revision ID: c61f130ec91a
Revises: 31d86b02db7c
Create Date: 2025-05-28 16:01:11.891423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61f130ec91a'
down_revision = '31d86b02db7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('fresh_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('facade_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('log_image', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('log_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('facade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fresh_img',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
