"""addTabelFissure

Revision ID: e86682f11745
Revises: 7094adb1cf96
Create Date: 2025-06-11 11:30:18.232152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86682f11745'
down_revision = '7094adb1cf96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fissure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fissure_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fissure')
    # ### end Alembic commands ###
