"""ReformulaModels

Revision ID: f05217167e05
Revises: 82b46ffa91a6
Create Date: 2025-05-26 17:07:51.467324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05217167e05'
down_revision = '82b46ffa91a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('images_building_id_fkey', type_='foreignkey')
        batch_op.drop_column('fachada')
        batch_op.drop_column('building_id')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('facade_id', sa.Integer(), nullable=True))

        batch_op.drop_constraint('logs_image_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'building', ['building_id'], ['id'])
        batch_op.create_foreign_key(None, 'facade', ['facade_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('mensage')
        batch_op.drop_column('datetime')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mensage', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('logs_image_id_fkey', 'images', ['image_id'], ['id'])
        batch_op.drop_column('facade_id')
        batch_op.drop_column('building_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('description')
        batch_op.drop_column('action')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fachada', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('images_building_id_fkey', 'building', ['building_id'], ['id'])

    op.drop_table('log_image')
    op.drop_table('facade')
    # ### end Alembic commands ###
