name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main] # ou a branch principal do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install
        working-directory: docs

      - name: Build do site
        run: npm run build
        working-directory: docs

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: docs
        env:
          GIT_USER: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
